# Generated by Django 4.2 on 2023-07-06 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cotent', models.TextField(max_length=30000)),
                ('date_post', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
